services:
  frontend:
    build: ./frontend
    #volumes:
    #  - ./frontend:/app
    networks:
      - lab-net

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - db
    networks:
      - lab-net

  db:
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - lab-net

  nginx:
    image: nginx:alpine
    platform: linux/amd64
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - lab-net

volumes:
  db_data:

networks:
  lab-net:
